import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const uploadSource = readFileSync(join(__dirname, '..', 'src', 'pages', 'report', 'Upload.vue'), 'utf8')
const detailSource = readFileSync(join(__dirname, '..', 'src', 'pages', 'report', 'Detail.vue'), 'utf8')
const manageSource = readFileSync(join(__dirname, '..', 'src', 'pages', 'report', 'Manage.vue'), 'utf8')
const reportStorageSource = readFileSync(join(__dirname, '..', 'src', 'services', 'reportStorage.js'), 'utf8')
const debtSource = readFileSync(join(__dirname, '..', 'src', 'pages', 'profile', 'DebtManage.vue'), 'utf8')
const pipelineSource = readFileSync(join(__dirname, '..', 'src', 'services', 'aiAnalysis', 'pipeline.js'), 'utf8')
const analysisTaskServiceSource = readFileSync(join(__dirname, '..', 'src', 'services', 'analysisTaskService.js'), 'utf8')
const routerSource = readFileSync(join(__dirname, '..', 'src', 'router', 'index.js'), 'utf8')
const reportExportSource = readFileSync(join(__dirname, '..', 'src', 'services', 'reportExport.js'), 'utf8')

describe('report detail and asset management user flow contract', () => {
  it('keeps report upload saving the new asset before opening detail', () => {
    assert.match(uploadSource, /import safeBack from '@\/utils\/safeBack\.js'/)
    assert.match(uploadSource, /const goBack = \(\) => safeBack\('\/pages\/home\/home'\)/)
    assert.match(uploadSource, /const analysisFile = fileType === 'image' && Array\.isArray\(picked\.files\) && picked\.files\.length/)
    assert.match(uploadSource, /picked\.file \|\| picked\.path/)
    assert.match(uploadSource, /analyzeCreditReport\(analysisFile, fileType, onProgress, \{[\s\S]*fileSize: picked\.size,[\s\S]*fileName: picked\.name,[\s\S]*files: picked\.files \|\| null/)
    assert.match(uploadSource, /const reportId = await saveReportDurable\(draftReport\)/)
    assert.match(uploadSource, /analysisJobId: remoteJobId/)
    assert.match(uploadSource, /reportType: \(data\.reportFormat && data\.reportFormat\.source\) \|\| '信用报告'/)
    assert.match(uploadSource, /await acknowledgeAnalysisJob\(remoteJobId, supportRef\)/)
    assert.match(uploadSource, /if \(acknowledged\) clearActiveAnalysisTask\(remoteJobId\)/)
    assert.match(reportStorageSource, /const analysisJobId = String\(_first\(reportData\.analysisJobId, reportData\.remoteJobId/)
    assert.match(reportStorageSource, /analysisJobId,[\s\S]*analysisResult: ar/)
    assert.match(reportStorageSource, /compactAnalysisForCloudUpload/)
    assert.doesNotMatch(reportStorageSource, /analysisResult:\s*reportData\.analysisData/)
    assert.match(uploadSource, /uni\.redirectTo\(\{[\s\S]*url: `\/pages\/report\/detail\?id=\$\{encodeURIComponent\(reportId\)\}`/)
  })

  it('keeps PDF and image uploads on the authoritative server path without client fallback', () => {
    assert.match(pipelineSource, /import \{ uploadCreditAnalyzeImages \} from '\.\.\/apiClient\.js'/)
    assert.match(pipelineSource, /createAnalysisJob,[\s\S]*getAnalysisJobResult,[\s\S]*saveActiveAnalysisTask,[\s\S]*waitForAnalysisJob/)
    assert.match(pipelineSource, /import \{ mapServerAnalyzeDataToClientAnalysis \} from '\.\.\/serverAnalyzeMapper\.js'/)
    assert.match(pipelineSource, /assertAuthoritativeServerAnalysis/)
    assert.match(pipelineSource, /executeAuthoritativeAnalysisPath/)
    assert.match(pipelineSource, /hasMeaningfulAnalysisData\(data\)/)
    assert.match(pipelineSource, /const authoritativeTask = await executeAuthoritativeAnalysisPath\(/)
    assert.match(pipelineSource, /runPdfServer: \(\) => tryFastServerPdfAnalyze\(/)
    assert.match(pipelineSource, /runImageServer: \(\) => tryFastServerImageAnalyze\(/)
    assert.match(pipelineSource, /return authoritativeTask/)
    assert.match(pipelineSource, /createAnalysisJob\(filePath, \{[\s\S]*onUploadProgress:/)
    assert.match(pipelineSource, /waitForAnalysisJob\(remoteJob\.jobId/)
		assert.match(pipelineSource, /import \{ createTerminalAnalysisFailure \} from '\.\.\/uploadFailure\.js'/)
		assert.match(pipelineSource, /throw createTerminalAnalysisFailure\(terminal, remoteJob\.jobId\)/)
		assert.doesNotMatch(pipelineSource, /Number\(terminal\.httpStatus\) \|\| 500/)
    assert.match(pipelineSource, /getAnalysisJobResult\(remoteJob\.jobId, terminal\.supportRef\)/)
    assert.match(pipelineSource, /uploadCreditAnalyzeImages\(imageFiles, \{ maxAttempts: 1 \}\)/)
    assert.match(pipelineSource, /const isAuthAnalyzeFailure = \(err\) =>/)
    assert.match(pipelineSource, /if \(isAuthAnalyzeFailure\(e\)\) \{[\s\S]*throw e/)
		assert.match(pipelineSource, /assertFastPdfOwnershipEvidence\(data\)/)
		assert.match(pipelineSource, /if \(isFastPdfOwnershipEvidenceFailure\(e\)\) throw e/)
    assert.doesNotMatch(pipelineSource, /PDF 快速分析失败，回退旧链路/)
  })

  it('keeps report list scores and risk labels behind the decision score gate', () => {
    assert.match(manageSource, /resolveV6ScoreDetails/)
    assert.match(manageSource, /resolved\.decisionEligible === true \? numberOrNull\(resolved\.score\) : null/)
    assert.match(manageSource, /trustedDecisionValue\(row\?\.decisionTrust \|\| null, 'riskLevel', 'riskLevel', expectedReportId\)/)
    assert.doesNotMatch(manageSource, /riskLevelFromDecisionScore\(score\)/)
    assert.doesNotMatch(manageSource, /row\?\.analysisData\?\.aiInsight\?\.total_score/)
    assert.doesNotMatch(manageSource, /row\?\.analysisResult\?\.report\?\.totalScore/)
    assert.doesNotMatch(reportStorageSource, /ad\?\.aiInsight\?\.risk_level/)
    assert.doesNotMatch(reportStorageSource, /ad\?\.kimiInsight\?\.risk_level/)
  })

  it('uses server task stages and real upload progress while labelling cache reuse truthfully', () => {
    assert.match(pipelineSource, /const SERVER_STAGE_UI = Object\.freeze\(\{/)
    assert.match(pipelineSource, /query_evidence: \{ step: 2/)
    assert.match(pipelineSource, /onUploadProgress: \(uploadProgress\) =>/)
		assert.match(pipelineSource, /saveActiveAnalysisTask\(\{[\s\S]*fileName: fileName \|\| '信用报告\.pdf',[\s\S]*reportFormat/)
		assert.match(pipelineSource, /reportFormat: remoteTask\.reportFormat[\s\S]*\? remoteTask\.reportFormat[\s\S]*: detectReportFormat\('pdf'\)/)
		assert.doesNotMatch(pipelineSource, /reportFormat: \{ type: 'PDF', source: '人行信用报告', version: 'unknown' \}/)
    assert.match(pipelineSource, /task\.progress = Math\.max\(task\.progress \|\| 0, Math\.min\(100, Number\(serverJob\.progress\) \|\| 0\)\)/)
    assert.doesNotMatch(pipelineSource, /startWaitingProgress\(task, onProgress, makeProgress\(5, totalSteps, 70\)\)/)
    assert.match(pipelineSource, /task\.steps\[1\]\.name = '服务端分析中'/)
    assert.match(uploadSource, /\{\{ currentStepName \|\| '正在读取报告结构' \}\}/)
    assert.match(pipelineSource, /execution\.cacheHit !== true/)
		assert.match(pipelineSource, /buildAnalysisExecutionViews\(resultExecution, remoteJob\)/)
		assert.match(pipelineSource, /analysisExecution: executionViews\.persisted/)
		assert.match(pipelineSource, /applyAnalysisExecutionToTask\(task, \{ analysisExecution: executionViews\.ui \}\)/)
		assert.doesNotMatch(pipelineSource, /analysisExecution: responseExecution/)
    assert.match(pipelineSource, /已复用同文件、同版本的已验证分析结果（未重复 OCR）/)
    assert.match(pipelineSource, /analysisExecution: null/)
    assert.match(uploadSource, /错误码：\{\{ errorCode \}\}/)
  })

  it('stops only the client watcher on page unload and resumes the persisted server task on re-entry', () => {
    assert.match(uploadSource, /import \{ onShow, onUnload \} from '@\/compat\/web-lifecycle\.js'/)
    assert.match(uploadSource, /const beginClientAnalysisWatch = \(\) =>/)
    assert.match(uploadSource, /signal: clientWatch\?\.signal/)
    assert.match(uploadSource, /resumeCreditAnalysisJob\(active, onProgress, \{ signal: clientWatch\?\.signal \}\)/)
    assert.match(uploadSource, /const latest = await getLatestAnalysisJob\(\)/)
    assert.match(uploadSource, /active = saveActiveAnalysisTask\(/)
    assert.match(uploadSource, /onUnload\(\(\) => \{[\s\S]*analysisAbortController\?\.abort\?\.\(\)/)
    assert.match(uploadSource, /e\.terminalAnalysisFailure === true/)
		assert.match(pipelineSource, /createTerminalAnalysisFailure\(terminal, remoteJob\.jobId\)/)
		assert.match(uploadSource, /const acknowledgeTerminalAnalysisFailure = async \(jobId, supportRef\) =>/)
		assert.match(uploadSource, /if \(acknowledged\) clearActiveAnalysisTask\(id\)/)
		const validationFailurePath = uploadSource.slice(
			uploadSource.indexOf('validatePickedFile(picked, fileType)'),
			uploadSource.indexOf('analyzing.value = true', uploadSource.indexOf('validatePickedFile(picked, fileType)'))
		)
		const initialAnalysisFailurePath = uploadSource.slice(
			uploadSource.indexOf('analyzing.value = true', uploadSource.indexOf('validatePickedFile(picked, fileType)')),
			uploadSource.indexOf('let resumeFlight = null')
		)
		assert.doesNotMatch(validationFailurePath, /acknowledgeTerminalAnalysisFailure/)
		assert.match(initialAnalysisFailurePath, /e\.terminalAnalysisFailure === true[\s\S]*e\.analysisJobId[\s\S]*await acknowledgeTerminalAnalysisFailure\(failedJobId, e\.supportRef\)/)
		assert.doesNotMatch(initialAnalysisFailurePath, /e\.analysisJobId \|\| active\?\.jobId/)
		assert.match(uploadSource, /String\(e\.analysisJobId \|\| ''\) === String\(active\.jobId \|\| ''\)/)
		assert.match(analysisTaskServiceSource, /responseJob\(await request\([\s\S]*\), id, expectedSupportRef\)/)
		assert.match(analysisTaskServiceSource, /ANALYSIS_TASK_RESPONSE_MISMATCH/)
		assert.equal((uploadSource.match(/await acknowledgeTerminalAnalysisFailure\(/g) || []).length, 2)
    assert.doesNotMatch(uploadSource, /if \(failureStage === 'analysis' && e && e\.code && e\.code !== 'ANALYSIS_POLL_ABORTED'\)/)
  })

	it('retries a completed report save through the persisted task instead of uploading again', () => {
		assert.match(uploadSource, /if \(errorCategory\.value === 'save'\) \{[\s\S]*resetState\(\)[\s\S]*void resumeActiveAnalysis\(\)[\s\S]*return/)
		assert.match(uploadSource, /failureStage = 'save'[\s\S]*await openCompletedReport\(task/)
		assert.match(uploadSource, /if \(acknowledged\) clearActiveAnalysisTask\(remoteJobId\)/)
	})

  it('exports the complete generated report as PDF, PNG, or JPG with the text watermark', () => {
    assert.match(detailSource, /import \{ REPORT_EXPORT_FORMATS, exportReportElement \} from '@\/services\/reportExport\.js'/)
    assert.doesNotMatch(detailSource, /from '@\/assets\/[^']*'/)
    assert.doesNotMatch(detailSource, /LogoUrl/)
    assert.match(detailSource, /ref="reportExportRoot"/)
    assert.match(detailSource, /data-report-export-root/)
    assert.match(detailSource, /const sectionVisible = \(id\) => exportMode\.value \|\|/)
    assert.match(detailSource, /v-if="sectionVisible\('sec-risk'\)"/)
    assert.match(detailSource, /v-if="sectionVisible\('sec-score'\)"/)
    assert.match(detailSource, /v-if="sectionVisible\('sec-debt'\)"/)
    assert.match(detailSource, /v-if="sectionVisible\('sec-query'\)"/)
    assert.match(detailSource, /v-if="sectionVisible\('sec-accounts'\)"/)
    assert.match(detailSource, /completenessExpanded\.value = true/)
    assert.match(detailSource, /scoreBasisExpanded\.value = true/)
    assert.match(detailSource, /activeQueryWindow\.value = '12m'/)
    assert.match(detailSource, /queryKindFilter\.value = 'all'/)
    assert.match(detailSource, /accountFilter\.value = 'all'/)
    assert.match(detailSource, /riskDropdownOpen\.value = false/)
    assert.match(detailSource, /exportMode\.value \? '全部风险明细'/)
    assert.match(detailSource, /if \(exportMode\.value\) \{\s*return \[\.\.\.riskHits\.value\]/)
    assert.match(detailSource, /exportMode\.value\s*\?\s*accounts\.value\s*:\s*filterAccountsForDetail/)
    assert.match(detailSource, /accountLimit\.value = Math\.max\(accountLimit\.value, filteredAccounts\.value\.length\)/)
    assert.match(detailSource, /riskHitLimit\.value = Math\.max\(riskHitLimit\.value, filteredRiskHits\.value\.length\)/)
    assert.match(detailSource, /queryRowLimit\.value = Math\.max\(queryRowLimit\.value, filteredQueryDetailSource\.value\.length\)/)
    const exportCall = detailSource.match(/exportReportElement\(root, \{[\s\S]*?\}\)/)
    assert.ok(exportCall, 'detail page must call exportReportElement with an option object')
    assert.match(exportCall[0], /format,/)
    assert.match(exportCall[0], /fileBaseName: `分析报告工作台-信用分析报告/)
    assert.match(exportCall[0], /logoUrl: null/)
    assert.doesNotMatch(exportCall[0], /logoUrl: (?!null)/)
    assert.match(reportExportSource, /if \(!logoUrl \|\| !ImageCtor\) return null/)
    assert.match(reportExportSource, /if \(!logo\) return drawFallbackLogo\(/)
    assert.match(reportExportSource, /fillText\('报', x \+ markSize \/ 2, markY \+ markSize \/ 2\)/)
    assert.match(reportExportSource, /fillText\('分析报告工作台', x \+ markSize \* 1\.28, y \+ height \* 0\.43\)/)
    assert.match(reportExportSource, /fillText\('信用材料协同系统', x \+ markSize \* 1\.3, y \+ height \* 0\.72\)/)
    assert.match(detailSource, /itemList: REPORT_EXPORT_FORMATS\.map\(\(item\) => item\.label\)/)
    assert.match(detailSource, /sheetRequest\.catch\(\(\) =>/)
    assert.match(detailSource, />\{\{ exporting \? '生成中…' : '下载报告' \}\}</)
    assert.match(detailSource, /data-report-export-exclude/)
  })

  it('fails closed when an explicitly requested report is missing or mismatched before export', () => {
    assert.match(detailSource, /const requestedReportIdOf = \(query = \{\}\) => queryText\(first\(query && query\.id, query && query\.reportId\)\)\.trim\(\)/)
    assert.match(detailSource, /const report = id \? await getReportAsync\(id\) : await getLatestReportAsync\(\)/)
    assert.doesNotMatch(detailSource, /if \(!report\) report = await getLatestReportAsync\(\)/)
    assert.match(detailSource, /requestedReportMissing\.value = Boolean\(id\)/)
    assert.match(detailSource, /为避免展示或下载其他客户的报告，系统不会自动切换到最新报告/)
    assert.match(detailSource, /if \(requestedId && activeId !== requestedId\) \{[\s\S]*报告归属校验失败/)
  })

  it('keeps report detail message landing and handling receipts wired', () => {
    assert.match(detailSource, /readMessageCenterViewState\(\)/)
    assert.match(detailSource, /saveMessageActionReceipt\(\{[\s\S]*\}, \{ stage, page: '\/pages\/report\/detail'/)
    assert.match(detailSource, /syncMessageActionReceipt\(receipt, saveMessageActionReceiptRemote\)/)
    assert.match(detailSource, /saveMessageCenterViewState\(\{[\s\S]*sourceMessageId/)
    assert.match(detailSource, /markMessageLanded\(\)/)
    assert.match(detailSource, /@click="markMessageHandled"/)
    assert.match(detailSource, /const markMessageHandled = \(\) => \{/)
  })

  it('refreshes the report source badge when asynchronous cloud sync completes', () => {
    assert.match(reportStorageSource, /export const REPORT_SYNC_UPDATED_EVENT = 'rpt:report-sync-updated'/)
    assert.match(reportStorageSource, /uni\.\$emit\(REPORT_SYNC_UPDATED_EVENT, \{ reportId:/)
    assert.match(detailSource, /uni\.\$on\(REPORT_SYNC_UPDATED_EVENT, handleReportSyncUpdated\)/)
    assert.match(detailSource, /uni\.\$off\(REPORT_SYNC_UPDATED_EVENT, handleReportSyncUpdated\)/)
    assert.match(detailSource, /const refreshed = await getReportAsync\(changedId\)/)
    assert.match(detailSource, /if \(refreshed\) currentReport\.value = refreshed/)
    assert.match(detailSource, /title: '正在同步到云端'/)
    assert.match(detailSource, /title: '云端已同步'/)
    assert.match(detailSource, /onUnload\(\(\) => \{/)
  })

  it('keeps report detail handoffs to match, debt, message, and management flows wired', () => {
    assert.match(detailSource, /saveMatchReportContext\(currentReport\.value, isMessageRoute\.value \? 'message-detail' : 'detail', \{ messageContext: currentMessageContext\('match'\) \}\)/)
    assert.match(detailSource, /messageRouteQuery\('debt-manage'\)/)
    assert.match(detailSource, /query\.push\(`reportId=\$\{encodeURIComponent\(currentReportId\.value\)\}`\)/)
    assert.match(detailSource, /query\.push\('from=detail'\)/)
    assert.match(detailSource, /uni\.navigateTo\(\{ url: `\/pages\/profile\/debt-manage\$\{suffix\}`/)
    assert.match(detailSource, /const goMessageCenter = \(\) => safeSwitchTab\('\/pages\/message\/center'\)/)
    assert.match(detailSource, /const openReportManage = \(\) => uni\.navigateTo\(\{ url: '\/pages\/report\/manage'/)
    assert.match(detailSource, /DETAIL_CONTEXT_KEY = 'report_manage_detail_context'/)
    assert.match(detailSource, /const openContextReport = \(direction\) => \{/)
  })

	  it('keeps report management assets, cloud recovery, and detail context wired', () => {
	    assert.match(manageSource, /getCloudReportList\(1, 50\)/)
	    assert.match(manageSource, /import SwipeDelete from '@\/components\/SwipeDelete\.vue'/)
	    assert.match(manageSource, /<SwipeDelete[\s\S]*@delete="confirmSwipeDeleteReport\(row\)"/)
	    assert.match(manageSource, /管理员监测端仍会保留留档/)
	    assert.match(manageSource, /restoreCloudReportToLocal\(row\.raw \|\| row\.cloudId\)/)
	    assert.match(manageSource, /retryReportCloudSync\(row\.localId\)/)
	    assert.match(manageSource, /deleteCloudReport\(row\.cloudId\)/)
    assert.match(manageSource, /unlinkCloudReportFromLocal\(row\.localId, \{ cloudDeletedAt/)
    assert.match(manageSource, /DETAIL_CONTEXT_KEY = 'report_manage_detail_context'/)
    assert.match(manageSource, /uni\.setStorageSync\(DETAIL_CONTEXT_KEY, JSON\.stringify\(\{[\s\S]*items,/)
    assert.match(manageSource, /safeBack\(routeSource\.value === 'message' \? '\/pages\/message\/center' : '\/pages\/profile\/profile'\)/)
    assert.match(manageSource, /safeSwitchTab\('\/pages\/message\/center'\)/)
    assert.match(manageSource, /uni\.navigateTo\(\{ url: `\/pages\/report\/detail\?id=\$\{encodeURIComponent\(row\.localId\)\}&from=manage`/)
  })

  it('keeps debt management return paths tied to the active report asset', () => {
    assert.match(debtSource, /const goReportManage = \(\) => \{/)
    assert.match(debtSource, /id \? `reportId=\$\{encodeURIComponent\(id\)\}` : ''/)
    assert.match(debtSource, /const url = `\/pages\/report\/manage\$\{query \? '\?' \+ query : ''\}`/)
    assert.match(debtSource, /const goReportDetail = \(\) => \{/)
    assert.match(debtSource, /\/pages\/report\/detail\?id=\$\{encodeURIComponent\(id\)\}&from=debt/)
		assert.match(debtSource, /const requestedIds = resolveDecisionReportIdAliases\(\[query\.reportId, query\.id\], \{ requireMatch: true \}\)/)
		assert.match(debtSource, /routeRequestedReportId\.value = requestedIds && requestedIds\.length \? requestedIds\[0\] : ''/)
    assert.match(debtSource, /activeReportId\.value = routeRequestedReportId\.value/)
  })

  it('registers the report management page route', () => {
    assert.match(routerSource, /path: '\/pages\/report\/manage'/)
    assert.match(routerSource, /import\('@\/pages\/report\/Manage\.vue'\)/)
  })
})
